package model;

public class Carrello {

    /*@
    @ public invariant
    @ idVariante >= 0 &&
    @ pesoConfezione >= 0 &&
    @ quantita >= 0 &&
    @ prezzo >= 0;
    @ */
    private String emailUtente;

    private String idProdotto;
    private int idVariante;
    private String nomeProdotto;

    private String gusto;

    private int pesoConfezione;
    private String immagineProdotto;
    private int quantita;
    private float prezzo;


    //@ public pure;
    public String getEmailUtente() {
        return emailUtente;
    }
    /*@
    @ requires emailUtente != null;
    @ assignable this.emailUtente;
    @ ensures this.emailUtente.equals(emailUtente);
    @*/
    public void setEmailUtente(String emailUtente) {
        this.emailUtente = emailUtente;
    }


    //@ public pure;
    public String getIdProdotto() {
        return idProdotto;
    }
    /*@
    @ requires idProdotto != null;
    @ assignable this.idProdotto;
    @ ensures this.idProdotto.equals(idProdotto);
    @*/
    public void setIdProdotto(String idProdotto) {
        this.idProdotto = idProdotto;
    }


    //@ public pure;
    public int getIdVariante() {
        return idVariante;
    }
    /*@
    @ requires idVariante > 0;
    @ assignable this.idVariante;
    @ ensures this.idVariante == idVariante;
    @*/
    public void setIdVariante(int idVariante) {
        this.idVariante = idVariante;
    }


    //@ public pure;
    public String getNomeProdotto() {
        return nomeProdotto;
    }
    /*@
    @ requires nomeProdotto != null;
    @ assignable this.nomeProdotto;
    @ ensures this.nomeProdotto.equals(nomeProdotto);
    @*/
    public void setNomeProdotto(String nomeProdotto) {
        this.nomeProdotto = nomeProdotto;
    }


    //@ public pure;
    public int getQuantita() {
        return quantita;
    }
    /*@
    @ // Coerente con l'invariante, la quantità deve essere positiva.
    @ requires quantita > 0;
    @ assignable this.quantita;
    @ ensures this.quantita == quantita;
    @*/
    public void setQuantita(int quantita) {
        this.quantita = quantita;
    }


    //@ public pure;
    public float getPrezzo() {
        return prezzo;
    }
    /*@
    @ // Coerente con l'invariante, il prezzo non può essere negativo.
    @ requires prezzo >= 0;
    @ assignable this.prezzo;
    @ ensures this.prezzo == prezzo;
    @*/
    public void setPrezzo(float prezzo) {
        this.prezzo = prezzo;
    }


    //@ public pure;
    public String getGusto() {
        return gusto;
    }
    /*@
    @ requires gusto != null;
    @ assignable this.gusto;
    @ ensures this.gusto.equals(gusto);
    @*/
    public void setGusto(String gusto) {
        this.gusto = gusto;
    }


    //@ public pure;
    public int getPesoConfezione() {
        return pesoConfezione;
    }
    /*@
    @ requires pesoConfezione >= 0;
    @ assignable this.pesoConfezione;
    @ ensures this.pesoConfezione == pesoConfezione;
    @*/
    public void setPesoConfezione(int pesoConfezione) {
        this.pesoConfezione = pesoConfezione;
    }


    //@ public pure;
    public String getImmagineProdotto() {
        return immagineProdotto;
    }
    /*@
    @ requires immagineProdotto != null;
    @ assignable this.immagineProdotto;
    @ ensures this.immagineProdotto.equals(immagineProdotto);
    @*/
    public void setImmagineProdotto(String immagineProdotto) {
        this.immagineProdotto = immagineProdotto;
    }


    //Auto-generated by Intellij
    //@ also
    //@ public pure;
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Carrello)) return false;

        Carrello carrello = (Carrello) o;

        if (getQuantita() != carrello.getQuantita()) return false;
        if (Float.compare(getPrezzo(), carrello.getPrezzo()) != 0) return false;
        if (getEmailUtente() != null ? !getEmailUtente().equals(carrello.getEmailUtente()) : carrello.getEmailUtente() != null)
            return false;
        if (getIdProdotto() != null ? !getIdProdotto().equals(carrello.getIdProdotto()) : carrello.getIdProdotto() != null)
            return false;
        return getNomeProdotto() != null ? getNomeProdotto().equals(carrello.getNomeProdotto()) : carrello.getNomeProdotto() == null;
    }

    //Auto-generated by Intellij
    //@ also
    //@ public pure;
    @Override
    public int hashCode() {
        int result = getEmailUtente() != null ? getEmailUtente().hashCode() : 0;
        result = 31 * result + (getIdProdotto() != null ? getIdProdotto().hashCode() : 0);
        result = 31 * result + (getNomeProdotto() != null ? getNomeProdotto().hashCode() : 0);
        result = 31 * result + getQuantita();
        result = 31 * result + (getPrezzo() != 0.0f ? Float.floatToIntBits(getPrezzo()) : 0);
        return result;
    }

}


